apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: postgres-configurations
manifests:
  rawYaml:
    - auth-db/k8s/pg-init.yaml
    - auth-db/k8s/deployment.yaml
    - auth-db/k8s/service.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: auth-service
requires:
  - configs:
      - postgres-configurations
manifests:
  rawYaml:
    - auth-service/k8s/deployment.yaml
    - auth-service/k8s/service.yaml
build:
  local:
    concurrency: 0
  artifacts:
    - image: auth-service
      context: .
      docker:
        dockerfile: auth-service/Dockerfile
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: yap-api
requires:
  - configs:
      - auth-service
      - ingress-configurations
manifests:
  rawYaml:
    - yap-api/k8s/deployment.yaml 
    - yap-api/k8s/service.yaml
    - yap-api/k8s/ingress.yaml
build:
  local:
    concurrency: 0
  artifacts:
    - image: yap-api
      context: .
      docker:
        dockerfile: yap-api/Dockerfile
deploy:
  kubectl: {}
portForward:
  # This port-forwarding enables clients to connect to the yap-api service
  - resourceType: deployment
    resourceName: yap-api
    port: 50050
    localPort: 50050