apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE TABLE users
    (
        id       SERIAL PRIMARY KEY,
        username VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255)        NOT NULL
    );

    CREATE TABLE tokens
    (
        user_id       INTEGER REFERENCES users (id),
        access_token  VARCHAR(255) UNIQUE NOT NULL,
        refresh_token VARCHAR(255) UNIQUE NOT NULL,
        expires_at    TIMESTAMP           NOT NULL
    );