apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      initContainers:
        - name: wait-for-chat-db
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              until kubectl get svc chat-db; do
                echo "Waiting for chat-db service to be ready"
                sleep 5
              done
              until kubectl wait --for=condition=complete job/chat-db-init --timeout=120s; do
                echo "Waiting for chat-db-init job to complete"
                sleep 5
              done
      containers:
        - name: chat-service
          image: chat-service
          ports:
            - containerPort: 50051